//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeEditor.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResumeEditorEntities : DbContext
    {
        public ResumeEditorEntities()
            : base("name=ResumeEditorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MasterExperienceType> MasterExperienceTypes { get; set; }
        public virtual DbSet<MasterGender> MasterGenders { get; set; }
        public virtual DbSet<MasterMaritalStatu> MasterMaritalStatus { get; set; }
        public virtual DbSet<MasterSkillLevel> MasterSkillLevels { get; set; }
        public virtual DbSet<MasterSkillType> MasterSkillTypes { get; set; }
        public virtual DbSet<MasterTemplate> MasterTemplates { get; set; }
        public virtual DbSet<TransactionExperienceAchievement> TransactionExperienceAchievements { get; set; }
        public virtual DbSet<TransactionExperienceAchievementItem> TransactionExperienceAchievementItems { get; set; }
        public virtual DbSet<TransactionExperienceTimeline> TransactionExperienceTimelines { get; set; }
        public virtual DbSet<TransactionJobDescription> TransactionJobDescriptions { get; set; }
        public virtual DbSet<TransactionOwnerHobbyAndLiftStyle> TransactionOwnerHobbyAndLiftStyles { get; set; }
        public virtual DbSet<TransactionOwnerOverView> TransactionOwnerOverViews { get; set; }
        public virtual DbSet<TransactionOwnerProfile> TransactionOwnerProfiles { get; set; }
        public virtual DbSet<TransactionOwnerSkill> TransactionOwnerSkills { get; set; }
        public virtual DbSet<TransactionResumeDocument> TransactionResumeDocuments { get; set; }
        public virtual DbSet<TransactionResumeHobbyAndLiftStyle> TransactionResumeHobbyAndLiftStyles { get; set; }
        public virtual DbSet<TransactionResumeOverView> TransactionResumeOverViews { get; set; }
        public virtual DbSet<vwExperienceAchievement> vwExperienceAchievements { get; set; }
    }
}
