//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeEditor.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionExperienceAchievement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionExperienceAchievement()
        {
            this.TransactionExperienceAchievementItems = new HashSet<TransactionExperienceAchievementItem>();
        }
    
        public int Id { get; set; }
        public string OwnerId { get; set; }
        public string ExperienceId { get; set; }
        public string AchievementId { get; set; }
        public string AchievementTitle { get; set; }
        public string AchievementDescription { get; set; }
        public Nullable<int> AchievementSequence { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual TransactionExperienceTimeline TransactionExperienceTimeline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionExperienceAchievementItem> TransactionExperienceAchievementItems { get; set; }
    }
}
