//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeEditor.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionResumeDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionResumeDocument()
        {
            this.TransactionResumeHobbyAndLiftStyles = new HashSet<TransactionResumeHobbyAndLiftStyle>();
            this.TransactionResumeOverViews = new HashSet<TransactionResumeOverView>();
        }
    
        public int Id { get; set; }
        public string ResumeDocumentId { get; set; }
        public string OwnerId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public string ApplyingFor { get; set; }
        public string TemplateId { get; set; }
        public string Reference1 { get; set; }
    
        public virtual MasterTemplate MasterTemplate { get; set; }
        public virtual TransactionOwnerProfile TransactionOwnerProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionResumeHobbyAndLiftStyle> TransactionResumeHobbyAndLiftStyles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionResumeOverView> TransactionResumeOverViews { get; set; }
    }
}
