//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeEditor.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionOwnerSkill
    {
        public int Id { get; set; }
        public string OwnerId { get; set; }
        public string SkillId { get; set; }
        public string SkillTitle { get; set; }
        public string SkillDescription { get; set; }
        public Nullable<int> SkillLevelId { get; set; }
        public string SkillType { get; set; }
        public string SkillSinceYear { get; set; }
    
        public virtual MasterSkillLevel MasterSkillLevel { get; set; }
        public virtual MasterSkillType MasterSkillType { get; set; }
        public virtual TransactionOwnerProfile TransactionOwnerProfile { get; set; }
    }
}
