//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeEditor.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionJobDescription
    {
        public int Id { get; set; }
        public string OwnerId { get; set; }
        public string ExperienceId { get; set; }
        public string ItemId { get; set; }
        public string ItemTitle { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> ItemSequence { get; set; }
    
        public virtual TransactionExperienceTimeline TransactionExperienceTimeline { get; set; }
    }
}
