//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeEditor.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionExperienceTimeline
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionExperienceTimeline()
        {
            this.TransactionExperienceAchievements = new HashSet<TransactionExperienceAchievement>();
            this.TransactionJobDescriptions = new HashSet<TransactionJobDescription>();
        }
    
        public int Id { get; set; }
        public string OwnerId { get; set; }
        public string ExperienceId { get; set; }
        public string ExperienceType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string CompanyTitle { get; set; }
        public string PositionTitle { get; set; }
        public string CompanyAddress { get; set; }
    
        public virtual MasterExperienceType MasterExperienceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionExperienceAchievement> TransactionExperienceAchievements { get; set; }
        public virtual TransactionOwnerProfile TransactionOwnerProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionJobDescription> TransactionJobDescriptions { get; set; }
    }
}
