//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeEditor.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionOwnerProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionOwnerProfile()
        {
            this.TransactionExperienceTimelines = new HashSet<TransactionExperienceTimeline>();
            this.TransactionOwnerHobbyAndLiftStyles = new HashSet<TransactionOwnerHobbyAndLiftStyle>();
            this.TransactionOwnerOverViews = new HashSet<TransactionOwnerOverView>();
            this.TransactionOwnerSkills = new HashSet<TransactionOwnerSkill>();
            this.TransactionResumeDocuments = new HashSet<TransactionResumeDocument>();
        }
    
        public int Id { get; set; }
        public string OwnerId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string Email { get; set; }
        public string TelephoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Gender { get; set; }
        public string MaritalStatusId { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public Nullable<double> Height { get; set; }
        public string HeightUnit { get; set; }
        public Nullable<double> Weight { get; set; }
        public string WeightUnit { get; set; }
    
        public virtual MasterGender MasterGender { get; set; }
        public virtual MasterMaritalStatu MasterMaritalStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionExperienceTimeline> TransactionExperienceTimelines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionOwnerHobbyAndLiftStyle> TransactionOwnerHobbyAndLiftStyles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionOwnerOverView> TransactionOwnerOverViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionOwnerSkill> TransactionOwnerSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionResumeDocument> TransactionResumeDocuments { get; set; }
    }
}
