//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeEditor.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExperienceAchievement
    {
        public string ExperienceId { get; set; }
        public string AchievementId { get; set; }
        public string Year { get; set; }
        public string Project_No_ { get; set; }
        public string Project_Title { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<long> Row { get; set; }
        public string Description { get; set; }
        public string TagSkills { get; set; }
    }
}
